// utils/traducoes.dart
// Dicionário de traduções do mobile — equivalente ao translations.jsx da Web.
// Cada chave existe nos 3 idiomas. Se faltar uma chave num idioma, cai para
// PT; se faltar em PT também, mostra a própria chave (nunca rebenta).
//
// Convenção de nomenclatura das chaves: 'mobile_<ecrã>_<elemento>'.
// Chaves partilhadas entre vários ecrãs (botões, estados genéricos) usam só
// 'mobile_geral_<algo>', sem prefixo de ecrã.

class Traducoes {
  Traducoes._();

  static const Map<String, Map<String, String>> mapa = {
    'pt': {
      // ── Geral / partilhado ──────────────────────────────────────
      'mobile_geral_a_carregar': 'A carregar...',
      'mobile_geral_cancelar': 'Cancelar',
      'mobile_geral_guardar': 'Guardar',
      'mobile_geral_guardar_alteracoes': 'Guardar Alterações',
      'mobile_geral_confirmar': 'Confirmar',
      'mobile_geral_erro_desconhecido': 'Erro desconhecido',
      'mobile_geral_sem_ligacao': 'Sem ligação ao servidor.',
      'mobile_geral_ver_tudo': 'Ver Tudo',
      'mobile_geral_procurar': 'Procurar...',
      'mobile_geral_requisitos': 'Requisitos',

      // ── Login ────────────────────────────────────────────────────
      'mobile_login_email_label': 'Email',
      'mobile_login_email_hint': 'Insira o seu email',
      'mobile_login_email_obrigatorio': 'Por favor, insere o teu email',
      'mobile_login_email_invalido': 'Por favor, insira um email válido',
      'mobile_login_password_label': 'Password',
      'mobile_login_password_hint': 'Insira a sua password',
      'mobile_login_password_obrigatoria': 'Por favor, insira a sua password',
      'mobile_login_manter_sessao': 'Manter sessão iniciada',
      'mobile_login_esqueci_password': 'Esqueci-me da password',
      'mobile_login_entrar': 'Entrar',
      'mobile_login_sessao_expirada': 'A tua sessão expirou. Inicia sessão novamente.',

      // ── Dashboard ────────────────────────────────────────────────
      'mobile_dash_titulo': 'DASHBOARD',
      'mobile_dash_bom_dia': 'Bom dia',
      'mobile_dash_boa_tarde': 'Boa tarde',
      'mobile_dash_boa_noite': 'Boa noite',
      'mobile_dash_resumo_atividade': 'RESUMO DA MINHA ATIVIDADE',
      'mobile_dash_pedidos_pendentes': 'Pedidos\nPendentes',
      'mobile_dash_badges_conquistados': 'Badges\nConquistados',
      'mobile_dash_badges_especiais': 'Badges\nEspeciais',
      'mobile_dash_objetivos_alcancados': 'Objetivos\nAlcançados',
      'mobile_dash_objetivos_titulo': 'OBJETIVOS',
      'mobile_dash_objetivos_erro': 'Não foi possível carregar os objetivos.',
      'mobile_dash_objetivos_progresso_lp': 'Progresso na Learning Path',
      'mobile_dash_objetivos_em_progresso': 'Objetivos em progresso',
      'mobile_dash_objetivos_sem_curso': 'Sem objetivos em curso.',
      'mobile_dash_gamification_titulo': 'GAMIFICATION',
      'mobile_dash_ranking_vazio': 'Ainda sem ranking disponível.',
      'mobile_dash_desempenho_titulo': 'O teu desempenho',
      'mobile_dash_badges_recomendados_titulo': 'BADGES RECOMENDADOS',
      'mobile_dash_procurar_recomendados': 'Procurar nos badges recomendados...',
      'mobile_dash_badges_recomendados_erro': 'Não foi possível carregar as recomendações.',
      'mobile_dash_badges_recomendados_vazio': 'Já conquistaste todos os badges!',
      'mobile_dash_ranking_titulo': 'Ranking',
      'mobile_ola': 'Olá',
      'mobile_geral_tentar_novamente': 'Tentar novamente',
      'mobile_geral_procura_hint': 'Procura...',

      // ── PIN de recuperação de password ──────────────────────────
      'mobile_pin_insira_5_digitos': 'Insira os 5 dígitos.',
      'mobile_pin_titulo': 'Introduza o código:',
      'mobile_pin_subtitulo': 'Insira o código de 5 dígitos enviado para o seu email.',
      'mobile_pin_verificar': 'Verificar',

      // ── Ranking ──────────────────────────────────────────────────
      'mobile_ranking_titulo': 'RANKING',
      'mobile_ranking_erro': 'Não foi possível carregar o ranking.',
      'mobile_ranking_pesquisar_hint': 'Procurar consultor',
      'mobile_ranking_vazio': 'Nenhum consultor encontrado.',
      'mobile_ranking_pts': 'pts',
      'mobile_ranking_pontos': 'Pontos',

      // ── RGPD ─────────────────────────────────────────────────────
      'mobile_rgpd_erro_aceitar': 'Não foi possível registar a aceitação.',
      'mobile_rgpd_subtitulo': 'Antes de continuar, precisamos que confirmes que leste e aceitas a nossa Política de Privacidade.',
      'mobile_rgpd_indisponivel': 'Política de privacidade não disponível de momento.',
      'mobile_rgpd_aceitar_btn': 'Li e aceito a Política de Privacidade',
      'mobile_rgpd_sair_btn': 'Sair sem aceitar',

      // ── Configuração inicial ─────────────────────────────────────
      'mobile_config_inicial_seleciona_area': 'Seleciona a tua área para continuar.',
      'mobile_config_inicial_erro_guardar': 'Erro ao guardar. Tenta novamente.',
      'mobile_config_inicial_bemvindo': 'Bem-vindo!',
      'mobile_config_inicial_subtitulo': 'Escolhe a tua área para personalizarmos a tua experiência.',
      'mobile_config_inicial_continuar': 'Continuar',

      // ── Catálogo de badges ───────────────────────────────────────
      'mobile_catalogo_vazio': 'Nenhum badge encontrado.',
      'mobile_catalogo_titulo': 'CATÁLOGO',
      'mobile_catalogo_procurar_hint': 'Procura...',
      'mobile_catalogo_todas_areas': 'Todas as áreas',
      'mobile_catalogo_obtido': 'Obtido',

      // ── Trocar password (primeiro acesso) ───────────────────────
      'mobile_trocar_pass_erro': 'Erro ao alterar a password.',
      'mobile_trocar_pass_titulo': 'Define a tua nova palavra-passe',
      'mobile_trocar_pass_subtitulo': 'Por razões de segurança, tens de trocar a password temporária antes de continuar.',
      'mobile_trocar_pass_nova_label': 'Nova palavra-passe*',
      'mobile_trocar_pass_nova_hint': 'Mínimo 8 caracteres',
      'mobile_trocar_pass_nova_obrigatoria': 'Insere a nova palavra-passe',
      'mobile_trocar_pass_min_caracteres': 'A password deve ter pelo menos 8 caracteres.',
      'mobile_trocar_pass_repetir_label': 'Repete a palavra-passe*',
      'mobile_trocar_pass_repetir_obrigatoria': 'Repete a palavra-passe',
      'mobile_trocar_pass_nao_coincidem': 'As passwords não coincidem.',
      'mobile_trocar_pass_botao': 'Trocar password',

      // ── Badges (geral / expirados) ──────────────────────────────
      'mobile_badges_erro_carregar': 'Erro ao carregar badges',
      'mobile_badges_titulo': 'BADGES',
      'mobile_badges_nenhum_encontrado': 'Nenhum badge encontrado',
      'mobile_badges_sem_expirados': 'Não tens badges expirados',
      'mobile_badges_service_line': 'Service Line',
      'mobile_badges_area': 'Área',
      'mobile_badges_conquistado_em': 'Conquistado em:',
      'mobile_badges_expirou_em': 'Expirou em:',
      'mobile_badges_renovar': 'Renovar',
      'mobile_badges_expirado': 'Expirado',

      // ── Candidaturas a decorrer ──────────────────────────────────
      'mobile_cand_sem_encontradas': 'Sem candidaturas encontradas.',
      'mobile_cand_decorrer_titulo': 'A DECORRER',
      'mobile_cand_pesquisar_badge_hint': 'Pesquisar badge...',
      'mobile_cand_nivel_todos': 'Nível: Todos',
      'mobile_cand_tab_todos': 'Todos',
      'mobile_cand_tab_aguardar': 'A Aguardar',
      'mobile_cand_tab_corrigir': 'A Corrigir',

      // ── Os meus badges / expiração (partilhado) ──────────────────
      'mobile_badges_meus_titulo': 'OS MEUS BADGES',
      'mobile_badges_meus_sem_obtidos': 'Ainda não tens badges obtidos',
      'mobile_badges_sem_data_expiracao': 'Sem data de expiração',
      'mobile_badges_invalida': 'Badge inválida',
      'mobile_badges_expira_em': 'Expira em:',
      'mobile_badges_e': 'e',
      'mobile_badges_sem_especiais': 'Ainda não tens badges especiais',
      'mobile_badges_premium': 'Premium',
      'mobile_badges_badge_especial': 'Badge Especial',
      'mobile_badges_valido_ate': 'Válido até:',
      'mobile_badges_partilhar_linkedin': 'Partilhar no LinkedIn',
      'mobile_badges_descarregar_certificado': 'Descarregar Certificado',
      'mobile_badges_ver_pagina_publica': 'Ver página pública',
      'mobile_badges_assinatura_email': 'Adicionar à assinatura de email',
      'mobile_badges_assinatura_titulo': 'Assinatura de email',
      'mobile_badges_assinatura_desc': 'Copia este bloco e cola-o na tua assinatura de email (Outlook/Gmail).',
      'mobile_badges_assinatura_cargo': 'Consultor',
      'mobile_badges_assinatura_copiar': 'Copiar',
      'mobile_badges_assinatura_copiado': 'Copiado!',
      'mobile_badges_assinatura_fechar': 'Fechar',
      'mobile_badges_erro_certificado': 'Não foi possível gerar o certificado.',
      'mobile_badges_erro_linkedin': 'Não foi possível abrir o LinkedIn',
      'mobile_badges_sem_rgpd': 'Ainda não aceitaste os termos RGPD de publicação e partilha de badges. Aceita-os em Definições para poderes partilhar este badge.',
      'mobile_badges_erro_pagina': 'Não foi possível abrir a página',

      // ── Recuperar / redefinir password ────────────────────────────
      'mobile_recuperar_erro_enviar': 'Erro ao enviar código.',
      'mobile_recuperar_titulo': 'Introduza o seu email:',
      'mobile_recuperar_instrucao': 'Iremos enviar-lhe um pin para a recuperação da password.',
      'mobile_recuperar_email_obrigatorio': 'Insira o seu email',
      'mobile_recuperar_email_invalido': 'Email inválido',
      'mobile_recuperar_enviar': 'Enviar',
      'mobile_redefinir_sucesso_titulo': 'Sucesso!',
      'mobile_redefinir_sucesso_texto': 'A sua password foi redefinida com sucesso.',
      'mobile_redefinir_voltar_login': 'Voltar ao Login',
      'mobile_redefinir_titulo': 'Redefinir password:',
      'mobile_redefinir_nova_hint': 'Nova password',
      'mobile_redefinir_confirmar_hint': 'Confirmar password',
      'mobile_redefinir_botao': 'Redefinir',

      // ── Histórico de candidaturas ─────────────────────────────────
      'mobile_cand_historico_titulo': 'HISTÓRICO',
      'mobile_cand_tab_aprovados': 'Aprovados',
      'mobile_cand_tab_rejeitados': 'Rejeitados',
      'mobile_cand_tab_aprovados_singular': 'Aprovado',
      'mobile_cand_tab_rejeitados_singular': 'Rejeitado',
      'mobile_cand_nivel_label': 'Nível',
      'mobile_cand_criado_em': 'Criado em:',

      // ── Detalhe badge catálogo ───────────────────────────────────
      'mobile_geral_requisitos_maiusc': 'REQUISITOS',
      'mobile_catalogo_validade': 'Validade',
      'mobile_catalogo_dias': 'dias',
      'mobile_catalogo_sem_requisitos': 'Sem requisitos definidos para este badge.',
      'mobile_catalogo_ja_tens': 'Já tens este badge',
      'mobile_catalogo_candidatar': 'Candidatar-me',

      // ── Gamification ───────────────────────────────────────────────
      'mobile_gamif_meu_desempenho': 'O MEU DESEMPENHO',
      'mobile_gamif_ranking_completo': 'Ranking completo',
      'mobile_gamif_consultores': 'consultores',
      'mobile_gamif_posicao': 'POSIÇÃO',
      'mobile_gamif_de': 'de',
      'mobile_ranking_pontos_maiusc': 'PONTOS',
      'mobile_gamif_7_dias': '7 DIAS',
      'mobile_gamif_ranking_vazio': 'Ranking ainda vazio',
      'mobile_gamif_ranking_vazio_texto': 'Assim que houver badges atribuídos, o ranking aparece aqui.',
      'mobile_gamif_sem_ligacao': 'Sem ligação',
      'mobile_gamif_sem_ligacao_texto': 'O ranking precisa de ligação à internet para mostrar posições atualizadas.',

      // ── Notificações (lista) ───────────────────────────────────────
      'mobile_notif_eliminar_titulo': 'Eliminar notificação',
      'mobile_notif_eliminar_texto': 'Queres mesmo eliminar esta notificação? Esta ação não pode ser desfeita.',
      'mobile_notif_nao': 'Não',
      'mobile_notif_sim_eliminar': 'Sim, eliminar',
      'mobile_notif_erro_eliminar': 'Erro ao eliminar notificação.',
      'mobile_notif_sem_notificacoes': 'Sem notificações',
      'mobile_notif_titulo': 'NOTIFICAÇÕES',
      'mobile_notif_marcar_todas_lidas': 'Marcar todas como lidas',
      'mobile_notif_tab_todas': 'Todas',
      'mobile_notif_tab_nao_lidas': 'Não Lidas',

      // ── Tipos de notificação ────────────────────────────────────
      'mobile_notiftipo_aprovacao': 'Aprovado',
      'mobile_notiftipo_rejeicao': 'Rejeitado',
      'mobile_notiftipo_retificacao': 'Candidatura Devolvida',
      'mobile_notiftipo_candidatura_submetida': 'Candidatura Submetida',
      'mobile_notiftipo_em_validacao': 'Em Validação',
      'mobile_notiftipo_nova_candidatura': 'Nova Candidatura',
      'mobile_notiftipo_nova_validacao': 'Nova Validação',
      'mobile_notiftipo_badge_a_expirar': 'Badge a Expirar',
      'mobile_notiftipo_badge_expirado': 'Badge Expirado',
      'mobile_notiftipo_aviso': 'Aviso',
      'mobile_notiftipo_marco': 'Marco alcançado',
      'mobile_notiftipo_sla_ultrapassado': 'SLA Ultrapassado',
      'mobile_notiftipo_badges_a_expirar_tm': 'Badges a Expirar',
      'mobile_notiftipo_objetivo_prazo': 'Objetivo a Terminar',
      'mobile_notiftipo_defeito': 'Notificação',

      // ── Tempo relativo / agrupamento ─────────────────────────────
      'mobile_notif_tempo_agora': 'agora mesmo',
      'mobile_notif_sem_data': 'Data desconhecida',
      'mobile_notif_tempo_ha': 'há',
      'mobile_notif_tempo_min': 'min',
      'mobile_notif_grupo_hoje': 'Hoje',
      'mobile_notif_grupo_ontem': 'Ontem',
      'mobile_notif_grupo_semana': 'Esta Semana',
      'mobile_notif_grupo_antigas': 'Mais Antigas',

      // ── Detalhe da notificação ───────────────────────────────────
      'mobile_notifdet_titulo': 'NOTIFICAÇÃO',
      'mobile_notifdet_eliminar_confirmar': 'Tem a certeza que pretende eliminar esta notificação?',
      'mobile_notifdet_eliminar_botao': 'Eliminar',
      'mobile_notifdet_ver_candidatura': 'Ver candidatura',
      'mobile_notifdet_ver_badge': 'Ver badge',
      'mobile_notifdet_badge_nao_encontrado': 'Badge não encontrado.',
      'mobile_notifdet_ver_objetivos': 'Ver objetivos',
      'mobile_notifdet_nao_lida': 'Não lida',

      // ── Detalhe badge regular ────────────────────────────────────
      'mobile_badges_ver_requisitos': 'Ver requisitos',

      // ── Alterar password ──────────────────────────────────────────
      'mobile_alterar_pass_sucesso': 'Password alterada com sucesso.',
      'mobile_alterar_pass_erro': 'Erro ao alterar password.',
      'mobile_alterar_pass_titulo': 'Alterar Password',
      'mobile_alterar_pass_atual_label': 'Password atual',
      'mobile_alterar_pass_campo_obrigatorio': 'Campo obrigatório',
      'mobile_alterar_pass_nova_label': 'Nova password',
      'mobile_alterar_pass_confirmar_label': 'Confirmar nova password',

      // ── Novo objetivo ─────────────────────────────────────────────
      'mobile_novo_obj_titulo': 'NOVO OBJETIVO',
      'mobile_novo_obj_erro_tipos': 'Não foi possível carregar os tipos de objetivo.',
      'mobile_novo_obj_pergunta_tipo': 'Qual o tipo de objetivo?',
      'mobile_novo_obj_ate_quando': 'ATÉ QUANDO PRETENDES CONQUISTAR?',
      'mobile_novo_obj_data_placeholder': 'DD - MM - AAAA',
      'mobile_novo_obj_data_help': 'Data limite do objetivo',
      'mobile_novo_obj_escolhe_data': 'Escolhe uma data limite.',
      'mobile_novo_obj_erro_criar': 'Não foi possível criar o objetivo.',
      'mobile_novo_obj_sucesso_titulo': 'Novo objetivo definido!',
      'mobile_novo_obj_sucesso_ate': 'Tens até',
      'mobile_novo_obj_sucesso_conquistar': 'para o conquistares.',
      'mobile_novo_obj_continuar': 'Continuar',

      // ── Candidaturas (hub) ────────────────────────────────────────
      'mobile_cand_apagar_rascunho_titulo': 'Apagar rascunho?',
      'mobile_cand_apagar_rascunho_texto': 'Esta ação não pode ser desfeita. As evidências carregadas serão removidas.',
      'mobile_cand_sim_apagar': 'Sim, apagar',
      'mobile_cand_rascunho_apagado': 'Rascunho apagado.',
      'mobile_cand_erro_apagar': 'Erro ao apagar',
      'mobile_cand_hub_titulo': 'CANDIDATURAS',
      'mobile_cand_a_decorrer_singular': 'candidatura a decorrer',
      'mobile_cand_a_decorrer_plural': 'candidaturas a decorrer',
      'mobile_cand_em_progresso': 'EM PROGRESSO',
      'mobile_cand_sem_curso': 'Não tens candidaturas em curso.',
      'mobile_cand_nova': 'Nova Candidatura',
      'mobile_cand_sem_concluidas': 'Ainda não tens candidaturas concluídas.',
      'mobile_cand_rascunhos': 'RASCUNHOS',
      'mobile_cand_sem_dados': 'Sem dados.',
      'mobile_cand_ver_todos': 'VER TODOS',
      'mobile_cand_sem_nome': 'Sem nome',
      'mobile_cand_rascunho_chip': 'Rascunho',
      'mobile_cand_evidencias': 'evidências',
      'mobile_cand_continuar_botao': 'Continuar',

      // ── Os meus badges ────────────────────────────────────────────
      'mobile_meusbadges_recentes': 'RECENTES',
      'mobile_meusbadges_vazio_titulo': 'Ainda não tens badges',
      'mobile_meusbadges_vazio_subtitulo': 'Explora o catálogo e candidata-te ao teu primeiro badge.',
      'mobile_badges_especiais_maiusc': 'ESPECIAIS',
      'mobile_meusbadges_especiais_vazio_titulo': 'Sem badges especiais',
      'mobile_meusbadges_especiais_vazio_subtitulo': 'São atribuídos automaticamente ao atingires certas conquistas.',
      'mobile_meusbadges_expirados_maiusc': 'EXPIRADOS',
      'mobile_meusbadges_expirados_vazio_titulo': 'Nenhum badge expirado',
      'mobile_meusbadges_expirados_vazio_subtitulo': 'Os teus badges estão todos dentro da validade.',
      'mobile_meusbadges_validos': 'Válidos',
      'mobile_meusbadges_expirados': 'Expirados',
      'mobile_meusbadges_ver_disponiveis': 'Ver badges disponíveis',

      // ── Objetivos (lista) ─────────────────────────────────────────
      'mobile_obj_finalizados': 'FINALIZADOS',
      'mobile_obj_definir': 'Definir objetivo',
      'mobile_obj_erro_titulo': 'Não foi possível carregar',
      'mobile_obj_erro_texto': 'Verifica a ligação e tenta novamente.',
      'mobile_obj_vazio_progresso_titulo': 'Ainda não tens objetivos',
      'mobile_obj_vazio_progresso_texto': 'Define um objetivo para acompanhares o teu progresso ao longo do tempo.',
      'mobile_obj_vazio_finalizados_titulo': 'Sem objetivos finalizados',
      'mobile_obj_vazio_finalizados_texto': 'Os objetivos que concluíres aparecem aqui.',
      'mobile_obj_definido_em': 'Definido em',
      'mobile_obj_editar': 'Editar',
      'mobile_obj_remover': 'Remover',
      'mobile_obj_alcancado_em': 'Alcançado em',
      'mobile_obj_em_curso': 'Em curso',
      'mobile_obj_alcancado': 'Alcançado',
      'mobile_obj_nao_alcancado': 'Não alcançado',
      'mobile_obj_nova_data_limite': 'Nova data limite',
      'mobile_obj_atualizado': 'Objetivo atualizado.',
      'mobile_obj_erro_editar': 'Não foi possível editar.',
      'mobile_obj_remover_titulo': 'Remover objetivo',
      'mobile_obj_remover_confirmar': 'Queres mesmo remover',
      'mobile_obj_sim': 'Sim',
      'mobile_obj_removido': 'Objetivo removido.',
      'mobile_obj_erro_remover': 'Não foi possível remover.',
      'mobile_obj_prazo_terminado': 'Prazo terminado',
      'mobile_obj_termina_em': 'Termina em',
      'mobile_obj_dia': 'dia',
      'mobile_obj_dias': 'dias',

      // ── Detalhes da candidatura ───────────────────────────────────
      'mobile_detcand_erro_enviar_evidencia': 'Erro ao enviar evidência.',
      'mobile_detcand_reenviada_sucesso': 'Candidatura reenviada com sucesso!',
      'mobile_detcand_erro_reenviar': 'Erro ao reenviar candidatura.',
      'mobile_detcand_nao_encontrada': 'Candidatura não encontrada.',
      'mobile_detcand_requisitos_submetidos': 'REQUISITOS SUBMETIDOS',
      'mobile_detcand_timeline': 'TIMELINE',
      'mobile_detcand_titulo': 'CANDIDATURA',
      'mobile_detcand_badge_label': 'Badge:',
      'mobile_detcand_nivel_label': 'Nível:',
      'mobile_detcand_decisao_final': 'Decisão final:',
      'mobile_detcand_aviso_devolvida': 'Esta candidatura foi devolvida e precisa da tua ação.',
      'mobile_detcand_rever_candidatura': 'Rever Candidatura',
      'mobile_detcand_sem_requisitos': 'Sem requisitos definidos.',
      'mobile_detcand_submeter': 'Submeter',
      'mobile_detcand_sem_evidencia': 'Sem evidência',
      'mobile_detcand_pendente': 'Pendente',
      'mobile_detcand_sem_historico': 'Sem histórico disponível.',
      'mobile_detcand_incorreto': 'Incorreto',
      'mobile_detcand_correto': 'Correto',
      'mobile_detcand_decisao': 'Decisão:',
      'mobile_detcand_comentario': 'Comentário:',
      'mobile_mes_jan': 'Jan', 'mobile_mes_fev': 'Fev', 'mobile_mes_mar': 'Mar',
      'mobile_mes_abr': 'Abr', 'mobile_mes_mai': 'Mai', 'mobile_mes_jun': 'Jun',
      'mobile_mes_jul': 'Jul', 'mobile_mes_ago': 'Ago', 'mobile_mes_set': 'Set',
      'mobile_mes_out': 'Out', 'mobile_mes_nov': 'Nov', 'mobile_mes_dez': 'Dez',

      // ── Nova candidatura ──────────────────────────────────────────
      'mobile_novacand_rascunho_invalido': 'Dados do rascunho inválidos',
      'mobile_novacand_erro_carregar_rascunho': 'Não foi possível carregar este rascunho.',
      'mobile_novacand_erro_criar': 'Erro ao criar candidatura.',
      'mobile_novacand_submeter_titulo': 'Submeter candidatura?',
      'mobile_novacand_submeter_texto1': 'Vais candidatar-te ao badge',
      'mobile_novacand_submeter_texto2': 'Depois de submeteres, a candidatura segue para validação e já não poderás alterar as evidências.',
      'mobile_novacand_sim_submeter': 'Sim, submeter',
      'mobile_novacand_erro_submeter': 'Erro ao submeter candidatura.',
      'mobile_novacand_cancelar_titulo': 'Cancelar candidatura?',
      'mobile_novacand_sim_cancelar': 'Sim, cancelar',
      'mobile_novacand_cancelada': 'Candidatura cancelada.',
      'mobile_novacand_erro_cancelar': 'Erro ao cancelar candidatura.',
      'mobile_novacand_continuar_titulo': 'CONTINUAR RASCUNHO',
      'mobile_novacand_nova_titulo': 'NOVA CANDIDATURA',
      'mobile_novacand_service_line_label': 'Service line:',
      'mobile_novacand_area_label': 'Área:',
      'mobile_novacand_sem_requisitos': 'Este badge não tem requisitos definidos.',

      // ── Perfil ────────────────────────────────────────────────────
      'mobile_perfil_titulo': 'PERFIL',
      'mobile_perfil_erro_carregar': 'Erro ao carregar perfil',
      'mobile_perfil_consultor': 'CONSULTOR',
      'mobile_perfil_posicao_sufixo': 'ª Posição',
      'mobile_perfil_sem_posicao': '-- Posição',
      'mobile_perfil_informacoes': 'INFORMAÇÕES',
      'mobile_perfil_sem_telefone': 'Sem telefone',
      'mobile_perfil_sem_linkedin': 'Sem LinkedIn',
      'mobile_perfil_copiar_link': 'Copiar link',
      'mobile_perfil_link_copiado': 'Link copiado!',
      'mobile_perfil_erro_link': 'Não foi possível abrir o link.',
      'mobile_perfil_area': 'Área:',
      'mobile_perfil_learning_path': 'Learning Path:',
      'mobile_perfil_evolucao': 'EVOLUÇÃO PROFISSIONAL',
      'mobile_perfil_sem_conquistas': 'Ainda sem conquistas registadas.',
      'mobile_perfil_conquista_especial': 'Conquista Badge Especial:',
      'mobile_perfil_conquista': 'Conquista',
      'mobile_perfil_badges_titulo': 'BADGES',
      'mobile_perfil_tab_obtidos': 'Obtidos',
      'mobile_perfil_tab_progresso': 'Em Progresso',
      'mobile_perfil_tab_especiais': 'Especiais',
      'mobile_perfil_tab_historico': 'Histórico',
      'mobile_perfil_vazio_obtidos': 'Ainda não tens badges obtidos.',
      'mobile_perfil_vazio_especiais': 'Ainda não tens badges especiais.',
      'mobile_perfil_vazio_progresso': 'Sem candidaturas em progresso.',
      'mobile_perfil_vazio_historico': 'Ainda sem histórico.',
      'mobile_perfil_membro_desde': 'Membro desde:',
      'mobile_perfil_definicoes_botao': 'DEFINIÇÕES',

      // ── Ecrãs que tinham ficado por identificar ────────────────────
      'mobile_landing_inicio': 'Início',
      'mobile_candsub_titulo': 'Novo pedido submetido!',
      'mobile_candsub_texto': 'A tua candidatura foi submetida com sucesso e encontra-se agora em validação pelo Talent Manager.',
      'mobile_candsub_numero': 'Candidatura Nº',
      'mobile_candsub_ver_candidaturas': 'Ver Candidaturas',
      'mobile_camera_titulo': 'Câmara',

      // ── Widgets partilhados (lib/widgets) ───────────────────────────
      'mobile_geral_sem_rede_banner': 'Sem ligação à internet — a mostrar dados guardados',
      'mobile_geral_terminar_sessao': 'Terminar Sessão',
      'mobile_geral_terminar_sessao_confirmar': 'Pretende terminar a sua sessão?',
      'mobile_geral_clica_carregar': 'Clica para carregar',

      // Menu lateral (custom_drawer.dart)
      'mobile_drawer_dashboard': 'Dashboard',
      'mobile_drawer_meus_badges': 'Os Meus Badges',
      'mobile_drawer_catalogo': 'Catálogo de Badges',
      'mobile_drawer_candidaturas': 'Candidaturas',
      'mobile_drawer_objetivos': 'Os Meus Objetivos',
      'mobile_drawer_gamification': 'Gamification',
      'mobile_drawer_perfil': 'O Meu Perfil',

      // Celebração de marcos (celebracao_marco.dart)
      'mobile_marco_parabens': 'Parabéns!',
      'mobile_marco_boa': 'Boa!',
      'mobile_marco_badge_titulo_um': 'Novo badge conquistado!',
      'mobile_marco_badges_titulo_sufixo': 'novos badges!',
      'mobile_marco_badge_msg_um': 'Ganhaste mais um badge. Continua assim!',
      'mobile_marco_badges_msg_prefixo': 'Conquistaste',
      'mobile_marco_badges_msg_sufixo': 'badges desde a última visita.',
      'mobile_marco_especial_titulo': 'Conquista especial!',
      'mobile_marco_especial_msg_um': 'Desbloqueaste um badge especial pelo teu percurso.',
      'mobile_marco_especial_msg_varios_prefixo': 'Desbloqueaste',
      'mobile_marco_especial_msg_varios_sufixo': 'badges especiais.',
      'mobile_marco_objetivo_titulo_um': 'Objetivo alcançado!',
      'mobile_marco_objetivos_titulo_sufixo': 'objetivos alcançados!',
      'mobile_marco_objetivo_msg': 'Cumpriste o que tinhas proposto. Define o próximo!',
      'mobile_marco_patamar_prefixo': 'Marco:',
      'mobile_marco_patamar_badge_sufixo_singular': 'badge!',
      'mobile_marco_patamar_badge_sufixo_plural': 'badges!',
      'mobile_marco_patamar_badge_msg_um': 'Este é o teu primeiro badge na plataforma.',
      'mobile_marco_patamar_badge_msg_varios_prefixo': 'Já somas',
      'mobile_marco_patamar_badge_msg_varios_sufixo': 'badges conquistados.',
      'mobile_marco_patamar_pontos_sufixo': 'pontos!',
      'mobile_marco_patamar_pontos_msg_prefixo': 'Atingiste',
      'mobile_marco_patamar_pontos_msg_sufixo': 'pontos de gamification.',

      // Saudação de evento (saudacao_evento.dart)
      'mobile_saudacao_bemvindo': 'Bem-vindo!',
      'mobile_saudacao_bemvindo_novamente': 'Seja bem-vindo novamente!',
      'mobile_saudacao_primeiro_acesso_msg': 'Esta é a tua plataforma de badges. Explora o catálogo e candidata-te ao teu primeiro badge.',
      'mobile_saudacao_regresso_msg': 'Vê o que há de novo no catálogo desde a tua última visita.',
      'mobile_saudacao_ola_prefixo': 'Olá',
      'mobile_saudacao_regresso_prefixo': 'Que bom ver-te por cá outra vez,',
      'mobile_saudacao_vamos_la': 'Vamos lá',

      // Pódio (podio_ranking.dart)
      'mobile_podio_posicao_1': '1º',
      'mobile_podio_posicao_2': '2º',
      'mobile_podio_posicao_3': '3º',
    },
    'en': {
      // ── Geral / partilhado ──────────────────────────────────────
      'mobile_geral_a_carregar': 'Loading...',
      'mobile_geral_cancelar': 'Cancel',
      'mobile_geral_guardar': 'Save',
      'mobile_geral_guardar_alteracoes': 'Save Changes',
      'mobile_geral_confirmar': 'Confirm',
      'mobile_geral_erro_desconhecido': 'Unknown error',
      'mobile_geral_sem_ligacao': 'No connection to the server.',
      'mobile_geral_ver_tudo': 'See All',
      'mobile_geral_procurar': 'Search...',
      'mobile_geral_requisitos': 'Requirements',

      // ── Login ────────────────────────────────────────────────────
      'mobile_login_email_label': 'Email',
      'mobile_login_email_hint': 'Enter your email',
      'mobile_login_email_obrigatorio': 'Please enter your email',
      'mobile_login_email_invalido': 'Please enter a valid email',
      'mobile_login_password_label': 'Password',
      'mobile_login_password_hint': 'Enter your password',
      'mobile_login_password_obrigatoria': 'Please enter your password',
      'mobile_login_manter_sessao': 'Keep me signed in',
      'mobile_login_esqueci_password': 'Forgot my password',
      'mobile_login_entrar': 'Log in',
      'mobile_login_sessao_expirada': 'Your session has expired. Please log in again.',

      // ── Dashboard ────────────────────────────────────────────────
      'mobile_dash_titulo': 'DASHBOARD',
      'mobile_dash_bom_dia': 'Good morning',
      'mobile_dash_boa_tarde': 'Good afternoon',
      'mobile_dash_boa_noite': 'Good evening',
      'mobile_dash_resumo_atividade': 'SUMMARY OF MY ACTIVITY',
      'mobile_dash_pedidos_pendentes': 'Pending\nRequests',
      'mobile_dash_badges_conquistados': 'Badges\nEarned',
      'mobile_dash_badges_especiais': 'Special\nBadges',
      'mobile_dash_objetivos_alcancados': 'Goals\nAchieved',
      'mobile_dash_objetivos_titulo': 'GOALS',
      'mobile_dash_objetivos_erro': 'Could not load your goals.',
      'mobile_dash_objetivos_progresso_lp': 'Learning Path progress',
      'mobile_dash_objetivos_em_progresso': 'Goals in progress',
      'mobile_dash_objetivos_sem_curso': 'No goals in progress.',
      'mobile_dash_gamification_titulo': 'GAMIFICATION',
      'mobile_dash_ranking_vazio': 'No ranking available yet.',
      'mobile_dash_desempenho_titulo': 'Your performance',
      'mobile_dash_badges_recomendados_titulo': 'RECOMMENDED BADGES',
      'mobile_dash_procurar_recomendados': 'Search recommended badges...',
      'mobile_dash_badges_recomendados_erro': 'Could not load recommendations.',
      'mobile_dash_badges_recomendados_vazio': 'You have earned all badges!',
      'mobile_dash_ranking_titulo': 'Ranking',
      'mobile_ola': 'Hi',
      'mobile_geral_tentar_novamente': 'Try again',
      'mobile_geral_procura_hint': 'Search...',

      // ── PIN de recuperação de password ──────────────────────────
      'mobile_pin_insira_5_digitos': 'Enter the 5 digits.',
      'mobile_pin_titulo': 'Enter the code:',
      'mobile_pin_subtitulo': 'Enter the 5-digit code sent to your email.',
      'mobile_pin_verificar': 'Verify',

      // ── Ranking ──────────────────────────────────────────────────
      'mobile_ranking_titulo': 'RANKING',
      'mobile_ranking_erro': 'Could not load the ranking.',
      'mobile_ranking_pesquisar_hint': 'Search consultant',
      'mobile_ranking_vazio': 'No consultant found.',
      'mobile_ranking_pts': 'pts',
      'mobile_ranking_pontos': 'Points',

      // ── RGPD ─────────────────────────────────────────────────────
      'mobile_rgpd_erro_aceitar': 'Could not register your acceptance.',
      'mobile_rgpd_subtitulo': 'Before continuing, we need you to confirm that you have read and accept our Privacy Policy.',
      'mobile_rgpd_indisponivel': 'Privacy policy currently unavailable.',
      'mobile_rgpd_aceitar_btn': 'I have read and accept the Privacy Policy',
      'mobile_rgpd_sair_btn': 'Log out without accepting',

      // ── Configuração inicial ─────────────────────────────────────
      'mobile_config_inicial_seleciona_area': 'Select your area to continue.',
      'mobile_config_inicial_erro_guardar': 'Error saving. Please try again.',
      'mobile_config_inicial_bemvindo': 'Welcome!',
      'mobile_config_inicial_subtitulo': 'Choose your area so we can personalize your experience.',
      'mobile_config_inicial_continuar': 'Continue',

      // ── Catálogo de badges ───────────────────────────────────────
      'mobile_catalogo_vazio': 'No badge found.',
      'mobile_catalogo_titulo': 'CATALOG',
      'mobile_catalogo_procurar_hint': 'Search...',
      'mobile_catalogo_todas_areas': 'All areas',
      'mobile_catalogo_obtido': 'Earned',

      // ── Trocar password (primeiro acesso) ───────────────────────
      'mobile_trocar_pass_erro': 'Error changing the password.',
      'mobile_trocar_pass_titulo': 'Set your new password',
      'mobile_trocar_pass_subtitulo': 'For security reasons, you need to change the temporary password before continuing.',
      'mobile_trocar_pass_nova_label': 'New password*',
      'mobile_trocar_pass_nova_hint': 'Minimum 8 characters',
      'mobile_trocar_pass_nova_obrigatoria': 'Enter the new password',
      'mobile_trocar_pass_min_caracteres': 'The password must be at least 8 characters long.',
      'mobile_trocar_pass_repetir_label': 'Repeat the password*',
      'mobile_trocar_pass_repetir_obrigatoria': 'Repeat the password',
      'mobile_trocar_pass_nao_coincidem': 'Passwords do not match.',
      'mobile_trocar_pass_botao': 'Change password',

      // ── Badges (geral / expirados) ──────────────────────────────
      'mobile_badges_erro_carregar': 'Error loading badges',
      'mobile_badges_titulo': 'BADGES',
      'mobile_badges_nenhum_encontrado': 'No badge found',
      'mobile_badges_sem_expirados': 'You have no expired badges',
      'mobile_badges_service_line': 'Service Line',
      'mobile_badges_area': 'Area',
      'mobile_badges_conquistado_em': 'Earned on:',
      'mobile_badges_expirou_em': 'Expired on:',
      'mobile_badges_renovar': 'Renew',
      'mobile_badges_expirado': 'Expired',

      // ── Candidaturas a decorrer ──────────────────────────────────
      'mobile_cand_sem_encontradas': 'No applications found.',
      'mobile_cand_decorrer_titulo': 'IN PROGRESS',
      'mobile_cand_pesquisar_badge_hint': 'Search badge...',
      'mobile_cand_nivel_todos': 'Level: All',
      'mobile_cand_tab_todos': 'All',
      'mobile_cand_tab_aguardar': 'Pending',
      'mobile_cand_tab_corrigir': 'To Fix',

      // ── Os meus badges / expiração (partilhado) ──────────────────
      'mobile_badges_meus_titulo': 'MY BADGES',
      'mobile_badges_meus_sem_obtidos': 'You have not earned any badges yet',
      'mobile_badges_sem_data_expiracao': 'No expiration date',
      'mobile_badges_invalida': 'Invalid badge',
      'mobile_badges_expira_em': 'Expires in:',
      'mobile_badges_e': 'and',
      'mobile_badges_sem_especiais': 'You have no special badges yet',
      'mobile_badges_premium': 'Premium',
      'mobile_badges_badge_especial': 'Special Badge',
      'mobile_badges_valido_ate': 'Valid until:',
      'mobile_badges_partilhar_linkedin': 'Share on LinkedIn',
      'mobile_badges_descarregar_certificado': 'Download Certificate',
      'mobile_badges_ver_pagina_publica': 'View public page',
      'mobile_badges_assinatura_email': 'Add to email signature',
      'mobile_badges_assinatura_titulo': 'Email signature',
      'mobile_badges_assinatura_desc': 'Copy this block and paste it into your email signature (Outlook/Gmail).',
      'mobile_badges_assinatura_cargo': 'Consultant',
      'mobile_badges_assinatura_copiar': 'Copy',
      'mobile_badges_assinatura_copiado': 'Copied!',
      'mobile_badges_assinatura_fechar': 'Close',
      'mobile_badges_erro_certificado': 'Could not generate the certificate.',
      'mobile_badges_erro_linkedin': 'Could not open LinkedIn',
      'mobile_badges_sem_rgpd': 'You have not accepted the GDPR terms for badge publication and sharing yet. Accept them in Settings to share this badge.',
      'mobile_badges_erro_pagina': 'Could not open the page',

      // ── Recuperar / redefinir password ────────────────────────────
      'mobile_recuperar_erro_enviar': 'Error sending code.',
      'mobile_recuperar_titulo': 'Enter your email:',
      'mobile_recuperar_instrucao': 'We will send you a pin to recover your password.',
      'mobile_recuperar_email_obrigatorio': 'Enter your email',
      'mobile_recuperar_email_invalido': 'Invalid email',
      'mobile_recuperar_enviar': 'Send',
      'mobile_redefinir_sucesso_titulo': 'Success!',
      'mobile_redefinir_sucesso_texto': 'Your password has been reset successfully.',
      'mobile_redefinir_voltar_login': 'Back to Login',
      'mobile_redefinir_titulo': 'Reset password:',
      'mobile_redefinir_nova_hint': 'New password',
      'mobile_redefinir_confirmar_hint': 'Confirm password',
      'mobile_redefinir_botao': 'Reset',

      // ── Histórico de candidaturas ─────────────────────────────────
      'mobile_cand_historico_titulo': 'HISTORY',
      'mobile_cand_tab_aprovados': 'Approved',
      'mobile_cand_tab_rejeitados': 'Rejected',
      'mobile_cand_tab_aprovados_singular': 'Approved',
      'mobile_cand_tab_rejeitados_singular': 'Rejected',
      'mobile_cand_nivel_label': 'Level',
      'mobile_cand_criado_em': 'Created on:',

      // ── Detalhe badge catálogo ───────────────────────────────────
      'mobile_geral_requisitos_maiusc': 'REQUIREMENTS',
      'mobile_catalogo_validade': 'Validity',
      'mobile_catalogo_dias': 'days',
      'mobile_catalogo_sem_requisitos': 'No requirements defined for this badge.',
      'mobile_catalogo_ja_tens': 'You already have this badge',
      'mobile_catalogo_candidatar': 'Apply',

      // ── Gamification ───────────────────────────────────────────────
      'mobile_gamif_meu_desempenho': 'MY PERFORMANCE',
      'mobile_gamif_ranking_completo': 'Full ranking',
      'mobile_gamif_consultores': 'consultants',
      'mobile_gamif_posicao': 'RANK',
      'mobile_gamif_de': 'of',
      'mobile_ranking_pontos_maiusc': 'POINTS',
      'mobile_gamif_7_dias': '7 DAYS',
      'mobile_gamif_ranking_vazio': 'Ranking still empty',
      'mobile_gamif_ranking_vazio_texto': 'Once badges are awarded, the ranking will appear here.',
      'mobile_gamif_sem_ligacao': 'No connection',
      'mobile_gamif_sem_ligacao_texto': 'The ranking needs an internet connection to show updated positions.',

      // ── Notificações (lista) ───────────────────────────────────────
      'mobile_notif_eliminar_titulo': 'Delete notification',
      'mobile_notif_eliminar_texto': 'Do you really want to delete this notification? This action cannot be undone.',
      'mobile_notif_nao': 'No',
      'mobile_notif_sim_eliminar': 'Yes, delete',
      'mobile_notif_erro_eliminar': 'Error deleting notification.',
      'mobile_notif_sem_notificacoes': 'No notifications',
      'mobile_notif_titulo': 'NOTIFICATIONS',
      'mobile_notif_marcar_todas_lidas': 'Mark all as read',
      'mobile_notif_tab_todas': 'All',
      'mobile_notif_tab_nao_lidas': 'Unread',

      // ── Tipos de notificação ────────────────────────────────────
      'mobile_notiftipo_aprovacao': 'Approved',
      'mobile_notiftipo_rejeicao': 'Rejected',
      'mobile_notiftipo_retificacao': 'Application Returned',
      'mobile_notiftipo_candidatura_submetida': 'Application Submitted',
      'mobile_notiftipo_em_validacao': 'Under Review',
      'mobile_notiftipo_nova_candidatura': 'New Application',
      'mobile_notiftipo_nova_validacao': 'New Review',
      'mobile_notiftipo_badge_a_expirar': 'Badge Expiring',
      'mobile_notiftipo_badge_expirado': 'Badge Expired',
      'mobile_notiftipo_aviso': 'Notice',
      'mobile_notiftipo_marco': 'Milestone reached',
      'mobile_notiftipo_sla_ultrapassado': 'SLA Exceeded',
      'mobile_notiftipo_badges_a_expirar_tm': 'Badges Expiring',
      'mobile_notiftipo_objetivo_prazo': 'Goal Deadline Approaching',
      'mobile_notiftipo_defeito': 'Notification',

      // ── Tempo relativo / agrupamento ─────────────────────────────
      'mobile_notif_tempo_agora': 'just now',
      'mobile_notif_sem_data': 'Unknown date',
      'mobile_notif_tempo_ha': '',
      'mobile_notif_tempo_min': 'min ago',
      'mobile_notif_grupo_hoje': 'Today',
      'mobile_notif_grupo_ontem': 'Yesterday',
      'mobile_notif_grupo_semana': 'This Week',
      'mobile_notif_grupo_antigas': 'Older',

      // ── Detalhe da notificação ───────────────────────────────────
      'mobile_notifdet_titulo': 'NOTIFICATION',
      'mobile_notifdet_eliminar_confirmar': 'Are you sure you want to delete this notification?',
      'mobile_notifdet_eliminar_botao': 'Delete',
      'mobile_notifdet_ver_candidatura': 'View application',
      'mobile_notifdet_ver_badge': 'View badge',
      'mobile_notifdet_badge_nao_encontrado': 'Badge not found.',
      'mobile_notifdet_ver_objetivos': 'View goals',
      'mobile_notifdet_nao_lida': 'Unread',

      // ── Detalhe badge regular ────────────────────────────────────
      'mobile_badges_ver_requisitos': 'View requirements',

      // ── Alterar password ──────────────────────────────────────────
      'mobile_alterar_pass_sucesso': 'Password changed successfully.',
      'mobile_alterar_pass_erro': 'Error changing password.',
      'mobile_alterar_pass_titulo': 'Change Password',
      'mobile_alterar_pass_atual_label': 'Current password',
      'mobile_alterar_pass_campo_obrigatorio': 'Required field',
      'mobile_alterar_pass_nova_label': 'New password',
      'mobile_alterar_pass_confirmar_label': 'Confirm new password',

      // ── Novo objetivo ─────────────────────────────────────────────
      'mobile_novo_obj_titulo': 'NEW GOAL',
      'mobile_novo_obj_erro_tipos': 'Could not load goal types.',
      'mobile_novo_obj_pergunta_tipo': 'What type of goal?',
      'mobile_novo_obj_ate_quando': 'BY WHEN DO YOU WANT TO ACHIEVE IT?',
      'mobile_novo_obj_data_placeholder': 'DD - MM - YYYY',
      'mobile_novo_obj_data_help': 'Goal deadline',
      'mobile_novo_obj_escolhe_data': 'Choose a deadline.',
      'mobile_novo_obj_erro_criar': 'Could not create the goal.',
      'mobile_novo_obj_sucesso_titulo': 'New goal set!',
      'mobile_novo_obj_sucesso_ate': 'You have until',
      'mobile_novo_obj_sucesso_conquistar': 'to achieve it.',
      'mobile_novo_obj_continuar': 'Continue',

      // ── Candidaturas (hub) ────────────────────────────────────────
      'mobile_cand_apagar_rascunho_titulo': 'Delete draft?',
      'mobile_cand_apagar_rascunho_texto': 'This action cannot be undone. Uploaded evidence will be removed.',
      'mobile_cand_sim_apagar': 'Yes, delete',
      'mobile_cand_rascunho_apagado': 'Draft deleted.',
      'mobile_cand_erro_apagar': 'Error deleting',
      'mobile_cand_hub_titulo': 'APPLICATIONS',
      'mobile_cand_a_decorrer_singular': 'application in progress',
      'mobile_cand_a_decorrer_plural': 'applications in progress',
      'mobile_cand_em_progresso': 'IN PROGRESS',
      'mobile_cand_sem_curso': 'You have no applications in progress.',
      'mobile_cand_nova': 'New Application',
      'mobile_cand_sem_concluidas': 'You have no completed applications yet.',
      'mobile_cand_rascunhos': 'DRAFTS',
      'mobile_cand_sem_dados': 'No data.',
      'mobile_cand_ver_todos': 'SEE ALL',
      'mobile_cand_sem_nome': 'No name',
      'mobile_cand_rascunho_chip': 'Draft',
      'mobile_cand_evidencias': 'evidence',
      'mobile_cand_continuar_botao': 'Continue',

      // ── My badges ──────────────────────────────────────────────────
      'mobile_meusbadges_recentes': 'RECENT',
      'mobile_meusbadges_vazio_titulo': 'You have no badges yet',
      'mobile_meusbadges_vazio_subtitulo': 'Explore the catalog and apply for your first badge.',
      'mobile_badges_especiais_maiusc': 'SPECIAL',
      'mobile_meusbadges_especiais_vazio_titulo': 'No special badges',
      'mobile_meusbadges_especiais_vazio_subtitulo': 'These are awarded automatically when you reach certain achievements.',
      'mobile_meusbadges_expirados_maiusc': 'EXPIRED',
      'mobile_meusbadges_expirados_vazio_titulo': 'No expired badges',
      'mobile_meusbadges_expirados_vazio_subtitulo': 'All your badges are within their validity period.',
      'mobile_meusbadges_validos': 'Valid',
      'mobile_meusbadges_expirados': 'Expired',
      'mobile_meusbadges_ver_disponiveis': 'View available badges',

      // ── Goals (list) ─────────────────────────────────────────────
      'mobile_obj_finalizados': 'COMPLETED',
      'mobile_obj_definir': 'Set goal',
      'mobile_obj_erro_titulo': 'Could not load',
      'mobile_obj_erro_texto': 'Check your connection and try again.',
      'mobile_obj_vazio_progresso_titulo': 'You have no goals yet',
      'mobile_obj_vazio_progresso_texto': 'Set a goal to track your progress over time.',
      'mobile_obj_vazio_finalizados_titulo': 'No completed goals',
      'mobile_obj_vazio_finalizados_texto': 'Goals you complete will appear here.',
      'mobile_obj_definido_em': 'Set on',
      'mobile_obj_editar': 'Edit',
      'mobile_obj_remover': 'Remove',
      'mobile_obj_alcancado_em': 'Achieved on',
      'mobile_obj_em_curso': 'In progress',
      'mobile_obj_alcancado': 'Achieved',
      'mobile_obj_nao_alcancado': 'Not achieved',
      'mobile_obj_nova_data_limite': 'New deadline',
      'mobile_obj_atualizado': 'Goal updated.',
      'mobile_obj_erro_editar': 'Could not edit.',
      'mobile_obj_remover_titulo': 'Remove goal',
      'mobile_obj_remover_confirmar': 'Do you really want to remove',
      'mobile_obj_sim': 'Yes',
      'mobile_obj_removido': 'Goal removed.',
      'mobile_obj_erro_remover': 'Could not remove.',
      'mobile_obj_prazo_terminado': 'Deadline passed',
      'mobile_obj_termina_em': 'Ends in',
      'mobile_obj_dia': 'day',
      'mobile_obj_dias': 'days',

      // ── Application details ───────────────────────────────────────
      'mobile_detcand_erro_enviar_evidencia': 'Error uploading evidence.',
      'mobile_detcand_reenviada_sucesso': 'Application resubmitted successfully!',
      'mobile_detcand_erro_reenviar': 'Error resubmitting application.',
      'mobile_detcand_nao_encontrada': 'Application not found.',
      'mobile_detcand_requisitos_submetidos': 'SUBMITTED REQUIREMENTS',
      'mobile_detcand_timeline': 'TIMELINE',
      'mobile_detcand_titulo': 'APPLICATION',
      'mobile_detcand_badge_label': 'Badge:',
      'mobile_detcand_nivel_label': 'Level:',
      'mobile_detcand_decisao_final': 'Final decision:',
      'mobile_detcand_aviso_devolvida': 'This application was returned and needs your action.',
      'mobile_detcand_rever_candidatura': 'Review Application',
      'mobile_detcand_sem_requisitos': 'No requirements defined.',
      'mobile_detcand_submeter': 'Submit',
      'mobile_detcand_sem_evidencia': 'No evidence',
      'mobile_detcand_pendente': 'Pending',
      'mobile_detcand_sem_historico': 'No history available.',
      'mobile_detcand_incorreto': 'Incorrect',
      'mobile_detcand_correto': 'Correct',
      'mobile_detcand_decisao': 'Decision:',
      'mobile_detcand_comentario': 'Comment:',
      'mobile_mes_jan': 'Jan', 'mobile_mes_fev': 'Feb', 'mobile_mes_mar': 'Mar',
      'mobile_mes_abr': 'Apr', 'mobile_mes_mai': 'May', 'mobile_mes_jun': 'Jun',
      'mobile_mes_jul': 'Jul', 'mobile_mes_ago': 'Aug', 'mobile_mes_set': 'Sep',
      'mobile_mes_out': 'Oct', 'mobile_mes_nov': 'Nov', 'mobile_mes_dez': 'Dec',

      // ── New application ───────────────────────────────────────────
      'mobile_novacand_rascunho_invalido': 'Invalid draft data',
      'mobile_novacand_erro_carregar_rascunho': 'Could not load this draft.',
      'mobile_novacand_erro_criar': 'Error creating application.',
      'mobile_novacand_submeter_titulo': 'Submit application?',
      'mobile_novacand_submeter_texto1': 'You are about to apply for the badge',
      'mobile_novacand_submeter_texto2': 'Once submitted, the application goes to review and you will no longer be able to change the evidence.',
      'mobile_novacand_sim_submeter': 'Yes, submit',
      'mobile_novacand_erro_submeter': 'Error submitting application.',
      'mobile_novacand_cancelar_titulo': 'Cancel application?',
      'mobile_novacand_sim_cancelar': 'Yes, cancel',
      'mobile_novacand_cancelada': 'Application cancelled.',
      'mobile_novacand_erro_cancelar': 'Error cancelling application.',
      'mobile_novacand_continuar_titulo': 'CONTINUE DRAFT',
      'mobile_novacand_nova_titulo': 'NEW APPLICATION',
      'mobile_novacand_service_line_label': 'Service line:',
      'mobile_novacand_area_label': 'Area:',
      'mobile_novacand_sem_requisitos': 'This badge has no requirements defined.',

      // ── Profile ────────────────────────────────────────────────────
      'mobile_perfil_titulo': 'PROFILE',
      'mobile_perfil_erro_carregar': 'Error loading profile',
      'mobile_perfil_consultor': 'CONSULTANT',
      'mobile_perfil_posicao_sufixo': ' Position',
      'mobile_perfil_sem_posicao': '-- Position',
      'mobile_perfil_informacoes': 'INFORMATION',
      'mobile_perfil_sem_telefone': 'No phone',
      'mobile_perfil_sem_linkedin': 'No LinkedIn',
      'mobile_perfil_copiar_link': 'Copy link',
      'mobile_perfil_link_copiado': 'Link copied!',
      'mobile_perfil_erro_link': 'Could not open the link.',
      'mobile_perfil_area': 'Area:',
      'mobile_perfil_learning_path': 'Learning Path:',
      'mobile_perfil_evolucao': 'PROFESSIONAL EVOLUTION',
      'mobile_perfil_sem_conquistas': 'No achievements recorded yet.',
      'mobile_perfil_conquista_especial': 'Special Badge Achievement:',
      'mobile_perfil_conquista': 'Achievement',
      'mobile_perfil_badges_titulo': 'BADGES',
      'mobile_perfil_tab_obtidos': 'Earned',
      'mobile_perfil_tab_progresso': 'In Progress',
      'mobile_perfil_tab_especiais': 'Special',
      'mobile_perfil_tab_historico': 'History',
      'mobile_perfil_vazio_obtidos': 'You have no badges earned yet.',
      'mobile_perfil_vazio_especiais': 'You have no special badges yet.',
      'mobile_perfil_vazio_progresso': 'No applications in progress.',
      'mobile_perfil_vazio_historico': 'No history yet.',
      'mobile_perfil_membro_desde': 'Member since:',
      'mobile_perfil_definicoes_botao': 'SETTINGS',

      // ── Missing screens ─────────────────────────────────────────────
      'mobile_landing_inicio': 'Start',
      'mobile_candsub_titulo': 'New request submitted!',
      'mobile_candsub_texto': 'Your application has been successfully submitted and is now under review by the Talent Manager.',
      'mobile_candsub_numero': 'Application No.',
      'mobile_candsub_ver_candidaturas': 'View Applications',
      'mobile_camera_titulo': 'Camera',

      // ── Shared widgets (lib/widgets) ────────────────────────────────
      'mobile_geral_sem_rede_banner': 'No internet connection — showing saved data',
      'mobile_geral_terminar_sessao': 'Log Out',
      'mobile_geral_terminar_sessao_confirmar': 'Do you want to log out?',
      'mobile_geral_clica_carregar': 'Tap to upload',

      // Side menu (custom_drawer.dart)
      'mobile_drawer_dashboard': 'Dashboard',
      'mobile_drawer_meus_badges': 'My Badges',
      'mobile_drawer_catalogo': 'Badge Catalog',
      'mobile_drawer_candidaturas': 'Applications',
      'mobile_drawer_objetivos': 'My Goals',
      'mobile_drawer_gamification': 'Gamification',
      'mobile_drawer_perfil': 'My Profile',

      // Milestone celebration (celebracao_marco.dart)
      'mobile_marco_parabens': 'Congratulations!',
      'mobile_marco_boa': 'Nice!',
      'mobile_marco_badge_titulo_um': 'New badge earned!',
      'mobile_marco_badges_titulo_sufixo': 'new badges!',
      'mobile_marco_badge_msg_um': 'You earned another badge. Keep it up!',
      'mobile_marco_badges_msg_prefixo': 'You earned',
      'mobile_marco_badges_msg_sufixo': 'badges since your last visit.',
      'mobile_marco_especial_titulo': 'Special achievement!',
      'mobile_marco_especial_msg_um': 'You unlocked a special badge for your journey.',
      'mobile_marco_especial_msg_varios_prefixo': 'You unlocked',
      'mobile_marco_especial_msg_varios_sufixo': 'special badges.',
      'mobile_marco_objetivo_titulo_um': 'Goal achieved!',
      'mobile_marco_objetivos_titulo_sufixo': 'goals achieved!',
      'mobile_marco_objetivo_msg': 'You did what you set out to do. Set the next one!',
      'mobile_marco_patamar_prefixo': 'Milestone:',
      'mobile_marco_patamar_badge_sufixo_singular': 'badge!',
      'mobile_marco_patamar_badge_sufixo_plural': 'badges!',
      'mobile_marco_patamar_badge_msg_um': 'This is your first badge on the platform.',
      'mobile_marco_patamar_badge_msg_varios_prefixo': "You've now earned",
      'mobile_marco_patamar_badge_msg_varios_sufixo': 'badges.',
      'mobile_marco_patamar_pontos_sufixo': 'points!',
      'mobile_marco_patamar_pontos_msg_prefixo': "You've reached",
      'mobile_marco_patamar_pontos_msg_sufixo': 'gamification points.',

      // Event greeting (saudacao_evento.dart)
      'mobile_saudacao_bemvindo': 'Welcome!',
      'mobile_saudacao_bemvindo_novamente': 'Welcome back!',
      'mobile_saudacao_primeiro_acesso_msg': 'This is your badge platform. Explore the catalog and apply for your first badge.',
      'mobile_saudacao_regresso_msg': "Check out what's new in the catalog since your last visit.",
      'mobile_saudacao_ola_prefixo': 'Hi',
      'mobile_saudacao_regresso_prefixo': 'Great to see you again,',
      'mobile_saudacao_vamos_la': "Let's go",

      // Podium (podio_ranking.dart)
      'mobile_podio_posicao_1': '1st',
      'mobile_podio_posicao_2': '2nd',
      'mobile_podio_posicao_3': '3rd',
    },
    'es': {
      // ── Geral / partilhado ──────────────────────────────────────
      'mobile_geral_a_carregar': 'Cargando...',
      'mobile_geral_cancelar': 'Cancelar',
      'mobile_geral_guardar': 'Guardar',
      'mobile_geral_guardar_alteracoes': 'Guardar Cambios',
      'mobile_geral_confirmar': 'Confirmar',
      'mobile_geral_erro_desconhecido': 'Error desconocido',
      'mobile_geral_sem_ligacao': 'Sin conexión al servidor.',
      'mobile_geral_ver_tudo': 'Ver Todo',
      'mobile_geral_procurar': 'Buscar...',
      'mobile_geral_requisitos': 'Requisitos',

      // ── Login ────────────────────────────────────────────────────
      'mobile_login_email_label': 'Email',
      'mobile_login_email_hint': 'Introduce tu email',
      'mobile_login_email_obrigatorio': 'Por favor, introduce tu email',
      'mobile_login_email_invalido': 'Por favor, introduce un email válido',
      'mobile_login_password_label': 'Contraseña',
      'mobile_login_password_hint': 'Introduce tu contraseña',
      'mobile_login_password_obrigatoria': 'Por favor, introduce tu contraseña',
      'mobile_login_manter_sessao': 'Mantener sesión iniciada',
      'mobile_login_esqueci_password': 'Olvidé mi contraseña',
      'mobile_login_entrar': 'Entrar',
      'mobile_login_sessao_expirada': 'Tu sesión ha caducado. Inicia sesión de nuevo.',

      // ── Dashboard ────────────────────────────────────────────────
      'mobile_dash_titulo': 'PANEL',
      'mobile_dash_bom_dia': 'Buenos días',
      'mobile_dash_boa_tarde': 'Buenas tardes',
      'mobile_dash_boa_noite': 'Buenas noches',
      'mobile_dash_resumo_atividade': 'RESUMEN DE MI ACTIVIDAD',
      'mobile_dash_pedidos_pendentes': 'Solicitudes\nPendientes',
      'mobile_dash_badges_conquistados': 'Badges\nConseguidos',
      'mobile_dash_badges_especiais': 'Badges\nEspeciales',
      'mobile_dash_objetivos_alcancados': 'Objetivos\nAlcanzados',
      'mobile_dash_objetivos_titulo': 'OBJETIVOS',
      'mobile_dash_objetivos_erro': 'No se pudieron cargar los objetivos.',
      'mobile_dash_objetivos_progresso_lp': 'Progreso en el Learning Path',
      'mobile_dash_objetivos_em_progresso': 'Objetivos en curso',
      'mobile_dash_objetivos_sem_curso': 'Sin objetivos en curso.',
      'mobile_dash_gamification_titulo': 'GAMIFICATION',
      'mobile_dash_ranking_vazio': 'Aún no hay ranking disponible.',
      'mobile_dash_desempenho_titulo': 'Tu rendimiento',
      'mobile_dash_badges_recomendados_titulo': 'BADGES RECOMENDADOS',
      'mobile_dash_procurar_recomendados': 'Buscar en las insignias recomendadas...',
      'mobile_dash_badges_recomendados_erro': 'No se pudieron cargar las recomendaciones.',
      'mobile_dash_badges_recomendados_vazio': '¡Ya has conseguido todos los badges!',
      'mobile_dash_ranking_titulo': 'Ranking',
      'mobile_ola': 'Hola',
      'mobile_geral_tentar_novamente': 'Intentar de nuevo',
      'mobile_geral_procura_hint': 'Buscar...',

      // ── PIN de recuperación de contraseña ───────────────────────
      'mobile_pin_insira_5_digitos': 'Introduce los 5 dígitos.',
      'mobile_pin_titulo': 'Introduce el código:',
      'mobile_pin_subtitulo': 'Introduce el código de 5 dígitos enviado a tu email.',
      'mobile_pin_verificar': 'Verificar',

      // ── Ranking ──────────────────────────────────────────────────
      'mobile_ranking_titulo': 'RANKING',
      'mobile_ranking_erro': 'No se pudo cargar el ranking.',
      'mobile_ranking_pesquisar_hint': 'Buscar consultor',
      'mobile_ranking_vazio': 'Ningún consultor encontrado.',
      'mobile_ranking_pts': 'pts',
      'mobile_ranking_pontos': 'Puntos',

      // ── RGPD ─────────────────────────────────────────────────────
      'mobile_rgpd_erro_aceitar': 'No se pudo registrar la aceptación.',
      'mobile_rgpd_subtitulo': 'Antes de continuar, necesitamos que confirmes que has leído y aceptas nuestra Política de Privacidad.',
      'mobile_rgpd_indisponivel': 'Política de privacidad no disponible en este momento.',
      'mobile_rgpd_aceitar_btn': 'He leído y acepto la Política de Privacidad',
      'mobile_rgpd_sair_btn': 'Salir sin aceptar',

      // ── Configuración inicial ────────────────────────────────────
      'mobile_config_inicial_seleciona_area': 'Selecciona tu área para continuar.',
      'mobile_config_inicial_erro_guardar': 'Error al guardar. Inténtalo de nuevo.',
      'mobile_config_inicial_bemvindo': '¡Bienvenido!',
      'mobile_config_inicial_subtitulo': 'Elige tu área para personalizar tu experiencia.',
      'mobile_config_inicial_continuar': 'Continuar',

      // ── Catálogo de badges ───────────────────────────────────────
      'mobile_catalogo_vazio': 'No se encontró ningún badge.',
      'mobile_catalogo_titulo': 'CATÁLOGO',
      'mobile_catalogo_procurar_hint': 'Buscar...',
      'mobile_catalogo_todas_areas': 'Todas las áreas',
      'mobile_catalogo_obtido': 'Conseguido',

      // ── Cambiar contraseña (primer acceso) ──────────────────────
      'mobile_trocar_pass_erro': 'Error al cambiar la contraseña.',
      'mobile_trocar_pass_titulo': 'Define tu nueva contraseña',
      'mobile_trocar_pass_subtitulo': 'Por razones de seguridad, debes cambiar la contraseña temporal antes de continuar.',
      'mobile_trocar_pass_nova_label': 'Nueva contraseña*',
      'mobile_trocar_pass_nova_hint': 'Mínimo 8 caracteres',
      'mobile_trocar_pass_nova_obrigatoria': 'Introduce la nueva contraseña',
      'mobile_trocar_pass_min_caracteres': 'La contraseña debe tener al menos 8 caracteres.',
      'mobile_trocar_pass_repetir_label': 'Repite la contraseña*',
      'mobile_trocar_pass_repetir_obrigatoria': 'Repite la contraseña',
      'mobile_trocar_pass_nao_coincidem': 'Las contraseñas no coinciden.',
      'mobile_trocar_pass_botao': 'Cambiar contraseña',

      // ── Badges (general / expirados) ────────────────────────────
      'mobile_badges_erro_carregar': 'Error al cargar los badges',
      'mobile_badges_titulo': 'BADGES',
      'mobile_badges_nenhum_encontrado': 'Ningún badge encontrado',
      'mobile_badges_sem_expirados': 'No tienes badges caducados',
      'mobile_badges_service_line': 'Service Line',
      'mobile_badges_area': 'Área',
      'mobile_badges_conquistado_em': 'Conseguido el:',
      'mobile_badges_expirou_em': 'Caducó el:',
      'mobile_badges_renovar': 'Renovar',
      'mobile_badges_expirado': 'Caducado',

      // ── Solicitudes en curso ─────────────────────────────────────
      'mobile_cand_sem_encontradas': 'No se encontraron solicitudes.',
      'mobile_cand_decorrer_titulo': 'EN CURSO',
      'mobile_cand_pesquisar_badge_hint': 'Buscar badge...',
      'mobile_cand_nivel_todos': 'Nivel: Todos',
      'mobile_cand_tab_todos': 'Todos',
      'mobile_cand_tab_aguardar': 'Pendientes',
      'mobile_cand_tab_corrigir': 'Por Corregir',

      // ── Mis badges / caducidad (compartido) ───────────────────────
      'mobile_badges_meus_titulo': 'MIS BADGES',
      'mobile_badges_meus_sem_obtidos': 'Aún no has conseguido ningún badge',
      'mobile_badges_sem_data_expiracao': 'Sin fecha de caducidad',
      'mobile_badges_invalida': 'Badge no válido',
      'mobile_badges_expira_em': 'Caduca en:',
      'mobile_badges_e': 'y',
      'mobile_badges_sem_especiais': 'Aún no tienes badges especiales',
      'mobile_badges_premium': 'Premium',
      'mobile_badges_badge_especial': 'Badge Especial',
      'mobile_badges_valido_ate': 'Válido hasta:',
      'mobile_badges_partilhar_linkedin': 'Compartir en LinkedIn',
      'mobile_badges_descarregar_certificado': 'Descargar Certificado',
      'mobile_badges_ver_pagina_publica': 'Ver página pública',
      'mobile_badges_assinatura_email': 'Añadir a la firma de correo',
      'mobile_badges_assinatura_titulo': 'Firma de correo',
      'mobile_badges_assinatura_desc': 'Copia este bloque y pégalo en tu firma de correo (Outlook/Gmail).',
      'mobile_badges_assinatura_cargo': 'Consultor',
      'mobile_badges_assinatura_copiar': 'Copiar',
      'mobile_badges_assinatura_copiado': '¡Copiado!',
      'mobile_badges_assinatura_fechar': 'Cerrar',
      'mobile_badges_erro_certificado': 'No se pudo generar el certificado.',
      'mobile_badges_erro_linkedin': 'No se pudo abrir LinkedIn',
      'mobile_badges_sem_rgpd': 'Aún no has aceptado los términos RGPD de publicación y compartición de badges. Acéptalos en Ajustes para poder compartir este badge.',
      'mobile_badges_erro_pagina': 'No se pudo abrir la página',

      // ── Recuperar / restablecer contraseña ────────────────────────
      'mobile_recuperar_erro_enviar': 'Error al enviar el código.',
      'mobile_recuperar_titulo': 'Introduce tu email:',
      'mobile_recuperar_instrucao': 'Te enviaremos un pin para recuperar la contraseña.',
      'mobile_recuperar_email_obrigatorio': 'Introduce tu email',
      'mobile_recuperar_email_invalido': 'Email no válido',
      'mobile_recuperar_enviar': 'Enviar',
      'mobile_redefinir_sucesso_titulo': '¡Éxito!',
      'mobile_redefinir_sucesso_texto': 'Tu contraseña se ha restablecido correctamente.',
      'mobile_redefinir_voltar_login': 'Volver al Login',
      'mobile_redefinir_titulo': 'Restablecer contraseña:',
      'mobile_redefinir_nova_hint': 'Nueva contraseña',
      'mobile_redefinir_confirmar_hint': 'Confirmar contraseña',
      'mobile_redefinir_botao': 'Restablecer',

      // ── Historial de solicitudes ──────────────────────────────────
      'mobile_cand_historico_titulo': 'HISTORIAL',
      'mobile_cand_tab_aprovados': 'Aprobadas',
      'mobile_cand_tab_rejeitados': 'Rechazadas',
      'mobile_cand_tab_aprovados_singular': 'Aprobada',
      'mobile_cand_tab_rejeitados_singular': 'Rechazada',
      'mobile_cand_nivel_label': 'Nivel',
      'mobile_cand_criado_em': 'Creado el:',

      // ── Detalle badge catálogo ────────────────────────────────────
      'mobile_geral_requisitos_maiusc': 'REQUISITOS',
      'mobile_catalogo_validade': 'Validez',
      'mobile_catalogo_dias': 'días',
      'mobile_catalogo_sem_requisitos': 'Sin requisitos definidos para este badge.',
      'mobile_catalogo_ja_tens': 'Ya tienes este badge',
      'mobile_catalogo_candidatar': 'Postularme',

      // ── Gamification ───────────────────────────────────────────────
      'mobile_gamif_meu_desempenho': 'MI RENDIMIENTO',
      'mobile_gamif_ranking_completo': 'Ranking completo',
      'mobile_gamif_consultores': 'consultores',
      'mobile_gamif_posicao': 'POSICIÓN',
      'mobile_gamif_de': 'de',
      'mobile_ranking_pontos_maiusc': 'PUNTOS',
      'mobile_gamif_7_dias': '7 DÍAS',
      'mobile_gamif_ranking_vazio': 'Ranking aún vacío',
      'mobile_gamif_ranking_vazio_texto': 'En cuanto se otorguen badges, el ranking aparecerá aquí.',
      'mobile_gamif_sem_ligacao': 'Sin conexión',
      'mobile_gamif_sem_ligacao_texto': 'El ranking necesita conexión a internet para mostrar posiciones actualizadas.',

      // ── Notificaciones (lista) ───────────────────────────────────
      'mobile_notif_eliminar_titulo': 'Eliminar notificación',
      'mobile_notif_eliminar_texto': '¿Seguro que quieres eliminar esta notificación? Esta acción no se puede deshacer.',
      'mobile_notif_nao': 'No',
      'mobile_notif_sim_eliminar': 'Sí, eliminar',
      'mobile_notif_erro_eliminar': 'Error al eliminar la notificación.',
      'mobile_notif_sem_notificacoes': 'Sin notificaciones',
      'mobile_notif_titulo': 'NOTIFICACIONES',
      'mobile_notif_marcar_todas_lidas': 'Marcar todas como leídas',
      'mobile_notif_tab_todas': 'Todas',
      'mobile_notif_tab_nao_lidas': 'No Leídas',

      // ── Tipos de notificación ────────────────────────────────────
      'mobile_notiftipo_aprovacao': 'Aprobada',
      'mobile_notiftipo_rejeicao': 'Rechazada',
      'mobile_notiftipo_retificacao': 'Solicitud Devuelta',
      'mobile_notiftipo_candidatura_submetida': 'Solicitud Enviada',
      'mobile_notiftipo_em_validacao': 'En Validación',
      'mobile_notiftipo_nova_candidatura': 'Nueva Solicitud',
      'mobile_notiftipo_nova_validacao': 'Nueva Validación',
      'mobile_notiftipo_badge_a_expirar': 'Badge a Caducar',
      'mobile_notiftipo_badge_expirado': 'Badge Caducado',
      'mobile_notiftipo_aviso': 'Aviso',
      'mobile_notiftipo_marco': 'Logro alcanzado',
      'mobile_notiftipo_sla_ultrapassado': 'SLA Superado',
      'mobile_notiftipo_badges_a_expirar_tm': 'Badges a Caducar',
      'mobile_notiftipo_objetivo_prazo': 'Objetivo por Vencer',
      'mobile_notiftipo_defeito': 'Notificación',

      // ── Tiempo relativo / agrupación ──────────────────────────────
      'mobile_notif_tempo_agora': 'ahora mismo',
      'mobile_notif_sem_data': 'Fecha desconocida',
      'mobile_notif_tempo_ha': 'hace',
      'mobile_notif_tempo_min': 'min',
      'mobile_notif_grupo_hoje': 'Hoy',
      'mobile_notif_grupo_ontem': 'Ayer',
      'mobile_notif_grupo_semana': 'Esta Semana',
      'mobile_notif_grupo_antigas': 'Más Antiguas',

      // ── Detalle de la notificación ────────────────────────────────
      'mobile_notifdet_titulo': 'NOTIFICACIÓN',
      'mobile_notifdet_eliminar_confirmar': '¿Seguro que quieres eliminar esta notificación?',
      'mobile_notifdet_eliminar_botao': 'Eliminar',
      'mobile_notifdet_ver_candidatura': 'Ver solicitud',
      'mobile_notifdet_ver_badge': 'Ver badge',
      'mobile_notifdet_badge_nao_encontrado': 'Badge no encontrado.',
      'mobile_notifdet_ver_objetivos': 'Ver objetivos',
      'mobile_notifdet_nao_lida': 'No leída',

      // ── Detalle badge regular ─────────────────────────────────────
      'mobile_badges_ver_requisitos': 'Ver requisitos',

      // ── Cambiar contraseña ──────────────────────────────────────
      'mobile_alterar_pass_sucesso': 'Contraseña cambiada con éxito.',
      'mobile_alterar_pass_erro': 'Error al cambiar la contraseña.',
      'mobile_alterar_pass_titulo': 'Cambiar Contraseña',
      'mobile_alterar_pass_atual_label': 'Contraseña actual',
      'mobile_alterar_pass_campo_obrigatorio': 'Campo obligatorio',
      'mobile_alterar_pass_nova_label': 'Nueva contraseña',
      'mobile_alterar_pass_confirmar_label': 'Confirmar nueva contraseña',

      // ── Nuevo objetivo ────────────────────────────────────────────
      'mobile_novo_obj_titulo': 'NUEVO OBJETIVO',
      'mobile_novo_obj_erro_tipos': 'No se pudieron cargar los tipos de objetivo.',
      'mobile_novo_obj_pergunta_tipo': '¿Qué tipo de objetivo?',
      'mobile_novo_obj_ate_quando': '¿PARA CUÁNDO QUIERES CONSEGUIRLO?',
      'mobile_novo_obj_data_placeholder': 'DD - MM - AAAA',
      'mobile_novo_obj_data_help': 'Fecha límite del objetivo',
      'mobile_novo_obj_escolhe_data': 'Elige una fecha límite.',
      'mobile_novo_obj_erro_criar': 'No se pudo crear el objetivo.',
      'mobile_novo_obj_sucesso_titulo': '¡Nuevo objetivo definido!',
      'mobile_novo_obj_sucesso_ate': 'Tienes hasta',
      'mobile_novo_obj_sucesso_conquistar': 'para conseguirlo.',
      'mobile_novo_obj_continuar': 'Continuar',

      // ── Solicitudes (hub) ─────────────────────────────────────────
      'mobile_cand_apagar_rascunho_titulo': '¿Eliminar borrador?',
      'mobile_cand_apagar_rascunho_texto': 'Esta acción no se puede deshacer. Las evidencias subidas se eliminarán.',
      'mobile_cand_sim_apagar': 'Sí, eliminar',
      'mobile_cand_rascunho_apagado': 'Borrador eliminado.',
      'mobile_cand_erro_apagar': 'Error al eliminar',
      'mobile_cand_hub_titulo': 'SOLICITUDES',
      'mobile_cand_a_decorrer_singular': 'solicitud en curso',
      'mobile_cand_a_decorrer_plural': 'solicitudes en curso',
      'mobile_cand_em_progresso': 'EN CURSO',
      'mobile_cand_sem_curso': 'No tienes solicitudes en curso.',
      'mobile_cand_nova': 'Nueva Solicitud',
      'mobile_cand_sem_concluidas': 'Aún no tienes solicitudes completadas.',
      'mobile_cand_rascunhos': 'BORRADORES',
      'mobile_cand_sem_dados': 'Sin datos.',
      'mobile_cand_ver_todos': 'VER TODAS',
      'mobile_cand_sem_nome': 'Sin nombre',
      'mobile_cand_rascunho_chip': 'Borrador',
      'mobile_cand_evidencias': 'evidencias',
      'mobile_cand_continuar_botao': 'Continuar',

      // ── Mis badges ─────────────────────────────────────────────────
      'mobile_meusbadges_recentes': 'RECIENTES',
      'mobile_meusbadges_vazio_titulo': 'Aún no tienes badges',
      'mobile_meusbadges_vazio_subtitulo': 'Explora el catálogo y postúlate para tu primer badge.',
      'mobile_badges_especiais_maiusc': 'ESPECIALES',
      'mobile_meusbadges_especiais_vazio_titulo': 'Sin badges especiales',
      'mobile_meusbadges_especiais_vazio_subtitulo': 'Se otorgan automáticamente al alcanzar ciertos logros.',
      'mobile_meusbadges_expirados_maiusc': 'CADUCADOS',
      'mobile_meusbadges_expirados_vazio_titulo': 'Ningún badge caducado',
      'mobile_meusbadges_expirados_vazio_subtitulo': 'Todos tus badges están dentro de su validez.',
      'mobile_meusbadges_validos': 'Válidos',
      'mobile_meusbadges_expirados': 'Caducados',
      'mobile_meusbadges_ver_disponiveis': 'Ver badges disponibles',

      // ── Objetivos (lista) ──────────────────────────────────────────
      'mobile_obj_finalizados': 'FINALIZADOS',
      'mobile_obj_definir': 'Definir objetivo',
      'mobile_obj_erro_titulo': 'No se pudo cargar',
      'mobile_obj_erro_texto': 'Comprueba la conexión e inténtalo de nuevo.',
      'mobile_obj_vazio_progresso_titulo': 'Aún no tienes objetivos',
      'mobile_obj_vazio_progresso_texto': 'Define un objetivo para seguir tu progreso a lo largo del tiempo.',
      'mobile_obj_vazio_finalizados_titulo': 'Sin objetivos finalizados',
      'mobile_obj_vazio_finalizados_texto': 'Los objetivos que completes aparecerán aquí.',
      'mobile_obj_definido_em': 'Definido el',
      'mobile_obj_editar': 'Editar',
      'mobile_obj_remover': 'Eliminar',
      'mobile_obj_alcancado_em': 'Alcanzado el',
      'mobile_obj_em_curso': 'En curso',
      'mobile_obj_alcancado': 'Alcanzado',
      'mobile_obj_nao_alcancado': 'No alcanzado',
      'mobile_obj_nova_data_limite': 'Nueva fecha límite',
      'mobile_obj_atualizado': 'Objetivo actualizado.',
      'mobile_obj_erro_editar': 'No se pudo editar.',
      'mobile_obj_remover_titulo': 'Eliminar objetivo',
      'mobile_obj_remover_confirmar': '¿Seguro que quieres eliminar',
      'mobile_obj_sim': 'Sí',
      'mobile_obj_removido': 'Objetivo eliminado.',
      'mobile_obj_erro_remover': 'No se pudo eliminar.',
      'mobile_obj_prazo_terminado': 'Plazo terminado',
      'mobile_obj_termina_em': 'Termina en',
      'mobile_obj_dia': 'día',
      'mobile_obj_dias': 'días',

      // ── Detalle de la solicitud ────────────────────────────────────
      'mobile_detcand_erro_enviar_evidencia': 'Error al enviar la evidencia.',
      'mobile_detcand_reenviada_sucesso': '¡Solicitud reenviada con éxito!',
      'mobile_detcand_erro_reenviar': 'Error al reenviar la solicitud.',
      'mobile_detcand_nao_encontrada': 'Solicitud no encontrada.',
      'mobile_detcand_requisitos_submetidos': 'REQUISITOS ENVIADOS',
      'mobile_detcand_timeline': 'CRONOLOGÍA',
      'mobile_detcand_titulo': 'SOLICITUD',
      'mobile_detcand_badge_label': 'Badge:',
      'mobile_detcand_nivel_label': 'Nivel:',
      'mobile_detcand_decisao_final': 'Decisión final:',
      'mobile_detcand_aviso_devolvida': 'Esta solicitud fue devuelta y necesita tu acción.',
      'mobile_detcand_rever_candidatura': 'Revisar Solicitud',
      'mobile_detcand_sem_requisitos': 'Sin requisitos definidos.',
      'mobile_detcand_submeter': 'Enviar',
      'mobile_detcand_sem_evidencia': 'Sin evidencia',
      'mobile_detcand_pendente': 'Pendiente',
      'mobile_detcand_sem_historico': 'Sin historial disponible.',
      'mobile_detcand_incorreto': 'Incorrecto',
      'mobile_detcand_correto': 'Correcto',
      'mobile_detcand_decisao': 'Decisión:',
      'mobile_detcand_comentario': 'Comentario:',
      'mobile_mes_jan': 'Ene', 'mobile_mes_fev': 'Feb', 'mobile_mes_mar': 'Mar',
      'mobile_mes_abr': 'Abr', 'mobile_mes_mai': 'May', 'mobile_mes_jun': 'Jun',
      'mobile_mes_jul': 'Jul', 'mobile_mes_ago': 'Ago', 'mobile_mes_set': 'Sep',
      'mobile_mes_out': 'Oct', 'mobile_mes_nov': 'Nov', 'mobile_mes_dez': 'Dic',

      // ── Nueva solicitud ────────────────────────────────────────────
      'mobile_novacand_rascunho_invalido': 'Datos del borrador no válidos',
      'mobile_novacand_erro_carregar_rascunho': 'No se pudo cargar este borrador.',
      'mobile_novacand_erro_criar': 'Error al crear la solicitud.',
      'mobile_novacand_submeter_titulo': '¿Enviar solicitud?',
      'mobile_novacand_submeter_texto1': 'Vas a postularte para el badge',
      'mobile_novacand_submeter_texto2': 'Una vez enviada, la solicitud pasa a validación y ya no podrás cambiar las evidencias.',
      'mobile_novacand_sim_submeter': 'Sí, enviar',
      'mobile_novacand_erro_submeter': 'Error al enviar la solicitud.',
      'mobile_novacand_cancelar_titulo': '¿Cancelar solicitud?',
      'mobile_novacand_sim_cancelar': 'Sí, cancelar',
      'mobile_novacand_cancelada': 'Solicitud cancelada.',
      'mobile_novacand_erro_cancelar': 'Error al cancelar la solicitud.',
      'mobile_novacand_continuar_titulo': 'CONTINUAR BORRADOR',
      'mobile_novacand_nova_titulo': 'NUEVA SOLICITUD',
      'mobile_novacand_service_line_label': 'Service line:',
      'mobile_novacand_area_label': 'Área:',
      'mobile_novacand_sem_requisitos': 'Este badge no tiene requisitos definidos.',

      // ── Perfil ────────────────────────────────────────────────────
      'mobile_perfil_titulo': 'PERFIL',
      'mobile_perfil_erro_carregar': 'Error al cargar el perfil',
      'mobile_perfil_consultor': 'CONSULTOR',
      'mobile_perfil_posicao_sufixo': 'ª Posición',
      'mobile_perfil_sem_posicao': '-- Posición',
      'mobile_perfil_informacoes': 'INFORMACIÓN',
      'mobile_perfil_sem_telefone': 'Sin teléfono',
      'mobile_perfil_sem_linkedin': 'Sin LinkedIn',
      'mobile_perfil_copiar_link': 'Copiar enlace',
      'mobile_perfil_link_copiado': '¡Enlace copiado!',
      'mobile_perfil_erro_link': 'No se pudo abrir el enlace.',
      'mobile_perfil_area': 'Área:',
      'mobile_perfil_learning_path': 'Learning Path:',
      'mobile_perfil_evolucao': 'EVOLUCIÓN PROFESIONAL',
      'mobile_perfil_sem_conquistas': 'Aún no hay logros registrados.',
      'mobile_perfil_conquista_especial': 'Logro Badge Especial:',
      'mobile_perfil_conquista': 'Logro',
      'mobile_perfil_badges_titulo': 'BADGES',
      'mobile_perfil_tab_obtidos': 'Conseguidos',
      'mobile_perfil_tab_progresso': 'En Progreso',
      'mobile_perfil_tab_especiais': 'Especiales',
      'mobile_perfil_tab_historico': 'Historial',
      'mobile_perfil_vazio_obtidos': 'Aún no has conseguido ningún badge.',
      'mobile_perfil_vazio_especiais': 'Aún no tienes badges especiales.',
      'mobile_perfil_vazio_progresso': 'Sin solicitudes en progreso.',
      'mobile_perfil_vazio_historico': 'Aún sin historial.',
      'mobile_perfil_membro_desde': 'Miembro desde:',
      'mobile_perfil_definicoes_botao': 'AJUSTES',

      // ── Pantallas que faltaban por identificar ─────────────────────
      'mobile_landing_inicio': 'Inicio',
      'mobile_candsub_titulo': '¡Nueva solicitud enviada!',
      'mobile_candsub_texto': 'Tu solicitud se ha enviado correctamente y está ahora en revisión por el Talent Manager.',
      'mobile_candsub_numero': 'Solicitud Nº',
      'mobile_candsub_ver_candidaturas': 'Ver Solicitudes',
      'mobile_camera_titulo': 'Cámara',

      // ── Widgets compartidos (lib/widgets) ───────────────────────────
      'mobile_geral_sem_rede_banner': 'Sin conexión a internet — mostrando datos guardados',
      'mobile_geral_terminar_sessao': 'Cerrar Sesión',
      'mobile_geral_terminar_sessao_confirmar': '¿Quieres cerrar la sesión?',
      'mobile_geral_clica_carregar': 'Toca para subir',

      // Menú lateral (custom_drawer.dart)
      'mobile_drawer_dashboard': 'Panel',
      'mobile_drawer_meus_badges': 'Mis Badges',
      'mobile_drawer_catalogo': 'Catálogo de Badges',
      'mobile_drawer_candidaturas': 'Solicitudes',
      'mobile_drawer_objetivos': 'Mis Objetivos',
      'mobile_drawer_gamification': 'Gamification',
      'mobile_drawer_perfil': 'Mi Perfil',

      // Celebración de logros (celebracao_marco.dart)
      'mobile_marco_parabens': '¡Enhorabuena!',
      'mobile_marco_boa': '¡Genial!',
      'mobile_marco_badge_titulo_um': '¡Nuevo badge conseguido!',
      'mobile_marco_badges_titulo_sufixo': 'badges nuevos!',
      'mobile_marco_badge_msg_um': 'Has conseguido otro badge. ¡Sigue así!',
      'mobile_marco_badges_msg_prefixo': 'Has conseguido',
      'mobile_marco_badges_msg_sufixo': 'badges desde tu última visita.',
      'mobile_marco_especial_titulo': '¡Logro especial!',
      'mobile_marco_especial_msg_um': 'Has desbloqueado un badge especial por tu trayectoria.',
      'mobile_marco_especial_msg_varios_prefixo': 'Has desbloqueado',
      'mobile_marco_especial_msg_varios_sufixo': 'badges especiales.',
      'mobile_marco_objetivo_titulo_um': '¡Objetivo alcanzado!',
      'mobile_marco_objetivos_titulo_sufixo': 'objetivos alcanzados!',
      'mobile_marco_objetivo_msg': 'Cumpliste lo que te propusiste. ¡Define el siguiente!',
      'mobile_marco_patamar_prefixo': 'Logro:',
      'mobile_marco_patamar_badge_sufixo_singular': 'badge!',
      'mobile_marco_patamar_badge_sufixo_plural': 'badges!',
      'mobile_marco_patamar_badge_msg_um': 'Este es tu primer badge en la plataforma.',
      'mobile_marco_patamar_badge_msg_varios_prefixo': 'Ya sumas',
      'mobile_marco_patamar_badge_msg_varios_sufixo': 'badges conseguidos.',
      'mobile_marco_patamar_pontos_sufixo': 'puntos!',
      'mobile_marco_patamar_pontos_msg_prefixo': 'Alcanzaste',
      'mobile_marco_patamar_pontos_msg_sufixo': 'puntos de gamification.',

      // Saludo de evento (saudacao_evento.dart)
      'mobile_saudacao_bemvindo': '¡Bienvenido!',
      'mobile_saudacao_bemvindo_novamente': '¡Bienvenido de nuevo!',
      'mobile_saudacao_primeiro_acesso_msg': 'Esta es tu plataforma de badges. Explora el catálogo y postúlate para tu primer badge.',
      'mobile_saudacao_regresso_msg': 'Mira las novedades del catálogo desde tu última visita.',
      'mobile_saudacao_ola_prefixo': 'Hola',
      'mobile_saudacao_regresso_prefixo': 'Qué bueno verte de nuevo,',
      'mobile_saudacao_vamos_la': 'Vamos',

      // Podio (podio_ranking.dart)
      'mobile_podio_posicao_1': '1º',
      'mobile_podio_posicao_2': '2º',
      'mobile_podio_posicao_3': '3º',
    },
  };

  /// Traduz [chave] para [idioma]. Cai para PT se faltar no idioma pedido, e
  /// devolve a própria chave (nunca um ecrã em branco) se faltar em PT também.
  static String t(String idioma, String chave) {
    return mapa[idioma]?[chave] ?? mapa['pt']?[chave] ?? chave;
  }
}